"""initial schema

Revision ID: 882dacd5704e
Revises: 
Create Date: 2026-03-13 10:51:11.976810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882dacd5704e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_feature_flags_name_environment', 'feature_flags', ['name', 'environment'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nzdg_number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('membership_expiration', sa.DateTime(), nullable=True),
    sa.Column('membership_type', sa.Enum('FREE', 'PRO', 'AMATEUR', 'JUNIOR', 'LIFE', 'HONORARY', name='member_types'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nzdg_number')
    )
    op.create_index('ix_memberships_id_nzdg_number', 'memberships', ['id', 'nzdg_number'], unique=False)
    op.create_table('tour',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('major', sa.Boolean(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('island', sa.String(length=3), nullable=True),
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tour_events_tour_id', 'tour_events', ['tour_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kinde_id', sa.String(length=255), nullable=True),
    sa.Column('given_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('pdga_number', sa.Integer(), nullable=True),
    sa.Column('division', sa.String(length=4), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pdga_number')
    )
    op.create_index('ix_users_id_pdga_number', 'users', ['id', 'pdga_number'], unique=False)
    op.create_index('ix_users_kinde_id', 'users', ['kinde_id'], unique=False)
    op.create_index('ix_users_membership_id', 'users', ['membership_id'], unique=False)
    op.create_table('points_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('division', sa.String(length=5), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('event_points', sa.JSON(), nullable=False),
    sa.Column('all_events_played_and_points', sa.JSON(), nullable=False),
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_points_ledger_player_id', 'points_ledger', ['player_id'], unique=False)
    op.create_index('ix_points_ledger_player_id_division', 'points_ledger', ['player_id', 'division'], unique=False)
    op.create_index('ix_points_ledger_tour_id', 'points_ledger', ['tour_id'], unique=False)
    op.create_table('tour_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('tour_event_id', sa.UUID(), nullable=False),
    sa.Column('division', sa.String(length=4), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('membership_type', sa.Enum('FREE', 'PRO', 'AMATEUR', 'JUNIOR', 'LIFE', 'HONORARY', name='member_types'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tour_event_id'], ['tour_events.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tour_results_membership_type', 'tour_results', ['membership_type'], unique=False)
    op.create_index('ix_tour_results_player_id', 'tour_results', ['player_id'], unique=False)
    op.create_index('ix_tour_results_tour_event_id', 'tour_results', ['tour_event_id'], unique=False)
    op.create_index('ix_tour_results_tour_id', 'tour_results', ['tour_id'], unique=False)
    op.create_table('round_rating',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('tour_event_id', sa.UUID(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('tour_results_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tour_event_id'], ['tour_events.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['tour_results_id'], ['tour_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_round_rating_player_id', 'round_rating', ['player_id'], unique=False)
    op.create_index('ix_round_rating_tour_event_id', 'round_rating', ['tour_event_id'], unique=False)
    op.create_index('ix_round_rating_tour_id', 'round_rating', ['tour_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_round_rating_tour_id', table_name='round_rating')
    op.drop_index('ix_round_rating_tour_event_id', table_name='round_rating')
    op.drop_index('ix_round_rating_player_id', table_name='round_rating')
    op.drop_table('round_rating')
    op.drop_index('ix_tour_results_tour_id', table_name='tour_results')
    op.drop_index('ix_tour_results_tour_event_id', table_name='tour_results')
    op.drop_index('ix_tour_results_player_id', table_name='tour_results')
    op.drop_index('ix_tour_results_membership_type', table_name='tour_results')
    op.drop_table('tour_results')
    op.drop_index('ix_points_ledger_tour_id', table_name='points_ledger')
    op.drop_index('ix_points_ledger_player_id_division', table_name='points_ledger')
    op.drop_index('ix_points_ledger_player_id', table_name='points_ledger')
    op.drop_table('points_ledger')
    op.drop_index('ix_users_membership_id', table_name='users')
    op.drop_index('ix_users_kinde_id', table_name='users')
    op.drop_index('ix_users_id_pdga_number', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_tour_events_tour_id', table_name='tour_events')
    op.drop_table('tour_events')
    op.drop_table('tour')
    op.drop_index('ix_memberships_id_nzdg_number', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_feature_flags_name_environment', table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
